/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FunctionParser_FunctionParser */

#ifndef _Included_FunctionParser_FunctionParser
#define _Included_FunctionParser_FunctionParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FunctionParser_FunctionParser
 * Method:    yaccParse
 * Signature: (Ljava/lang/String;)[LFunctionParser/AbstractSyntaxTree;
 */
JNIEXPORT jobjectArray JNICALL Java_FunctionParser_FunctionParser_yaccParse
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
